//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNDWebsite
{
    public partial class _Default
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        protected global::System.Web.UI.WebControls.Button btnLogin;
        protected global::System.Web.UI.WebControls.Label lblWelcome;
        protected global::System.Web.UI.WebControls.Button btnLogout;
        protected global::System.Web.UI.WebControls.Button btnContact;
        protected global::System.Web.UI.WebControls.Label lblMessage;
        protected global::System.Web.UI.WebControls.Panel pnlProductsLink;
        protected global::System.Web.UI.WebControls.Panel pnlOrdersLink;
        protected global::System.Web.UI.WebControls.Panel pnlClientOrdersLink;
        protected global::System.Web.UI.WebControls.Panel pnlSuppliersLink;
        protected global::System.Web.UI.WebControls.Panel pnlSupplierProductsLink;
    }
}
