//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNDWebsite
{


    public partial class _Default
    {
        // Inside Default.aspx.designer.cs
        protected global::System.Web.UI.WebControls.Label lblMessage;

    }



}
