//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Manual edits to this file may be lost if regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNDWebsite
{
    public partial class Login
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.TextBox txtLoginEmail;
        protected global::System.Web.UI.WebControls.TextBox txtLoginPassword;

        protected global::System.Web.UI.WebControls.Button btnLogin;

        protected global::System.Web.UI.WebControls.TextBox txtSignupName;
        protected global::System.Web.UI.WebControls.TextBox txtSignupEmail;
        protected global::System.Web.UI.WebControls.TextBox txtSignupPassword;

        protected global::System.Web.UI.WebControls.Button btnSignup;

        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
