//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Manual edits may be lost if the file is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DNDWebsite
{
    public partial class Login
    {
        /// <summary>
        /// form1 control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        /// <summary>
        /// txtLoginEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLoginEmail;

        /// <summary>
        /// txtLoginPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLoginPassword;

        /// <summary>
        /// btnLogin control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnLogin;

        /// <summary>
        /// txtSignupName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSignupName;

        /// <summary>
        /// txtSignupEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSignupEmail;

        /// <summary>
        /// txtSignupPassword control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtSignupPassword;

        /// <summary>
        /// btnSignup control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button btnSignup;

        /// <summary>
        /// lblMessage control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Label lblMessage;
    }
}
